feat: adds unit summaries to listings list to backend
CityOfDetroit/bloom pull request #1077
Opened 2022-03-24 03:38 UTC by seanmalbert

## Issue

- Addresses #1059 in part

## Description

This adds unit summaries to the listings list for use on the frontend browse and filtered pages.

## How Can This Be Tested/Reviewed?

Reseed the db locally and see that unitSummaries are on the listings.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-03-24 13:41 UTC, pbn4 requested changes

2022-03-24 13:41 UTC, pbn4 commented on backend/core/src/listings/listings.service.ts
> +    @InjectRepository(UnitGroup) private readonly unitGrouopRepository: Repository<UnitGroup>,
There is a typo in `Grouop`

2022-03-24 13:41 UTC, pbn4 commented on backend/core/src/shared/units-transformations.ts
> +  console.log("unitGroups = ", unitGroups)
Can be removed

2022-03-24 13:41 UTC, pbn4 commented on backend/core/src/listings/listings.service.ts
> +    const unitGroupMap = res.reduce((obj, current) => {
Could use typing `Record<string, Array<UnitGroup>>`

2022-03-24 13:41 UTC, pbn4 commented on backend/core/src/units-summary/entities/unit-group.entity.ts
> +  @IsOptional({ groups: [ValidationsGroupsEnum.default] })
I think it's not optional, is it?

2022-03-29 01:18 UTC, seanmalbert commented
@pbn4 ,
I've addressed your changes. There are also a couple of unrelated updates, cleaning assets for seeds and a fix on the public side I noticed.

2022-03-29 09:25 UTC, pbn4 approved these changes

2022-04-05 02:20 UTC, merged