feat: updated content & styles on homepage, footer
CityOfDetroit/bloom pull request #1134
Opened 2022-04-11 19:14 UTC by jaredcwhite

## Issue

- Closes #1060 
- Closes #1111 

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-04-13 23:16 UTC, emilyjablonski commented
@slowbot The design linked in these issues contradicts some of the design updates we have made recently. I know we recently touched based on what the listing cards should look like on the homepage from [this Figma](https://www.figma.com/file/D2fNPS5Ucll8uz7hyMUQGB/bloom-public-single-listing?node-id=1844%3A20246) - which is correct?

2022-04-14 15:21 UTC, seanmalbert approved these changes
LGTM. FYI, I merged in latest dev and resolved conflicts with sites/public/page_content/locale_overrides/general.json and sites/public/styles/overrides.scss

2022-04-17 18:12 UTC, YazeedLoonat requested changes
Hey @jaredcwhite, looks good a few things that I think should be covered by this, but if not just lemme know: 

1) the very top bar (for language selection) I think is the wrong color
2) City Regions carousel should be before the `sign up today` and `view resources`
3) not sure on this one but the background image for `see all rentals`
4) the verbiage for the `view resources` section
5) verbiage around `For listing and application questions:` seems wrong
6) verbiage around `For general program inquiries:` seems wrong
7) `For general program inquiries:` email and phone number shouldn't be bold 
8) should the `City of Detroit © 2021` be `City of Detroit © 2022` ?

2022-04-18 16:07 UTC, emilyjablonski commented
![Screen Shot 2022-04-18 at 10 06 53 AM](https://user-images.githubusercontent.com/65367387/163837065-b118d175-c5ef-422e-a6a2-022e58c12635.png)
touched base offline with @slowbot, we will be adding back this latest listings scroll piece, so we'd like to just comment it out and not remove it so that it's easy to add back in later

2022-04-18 19:19 UTC, jaredcwhite commented
Thanks @YazeedLoonat for noticing those discrepancies, I'll work on fixes.

@slowbot couple of questions for you:

> the very top bar (for language selection) I think is the wrong color

Is that right? Do we need to update the CSS for that?

And do we need to swap out a new background image for the hero? If so, can you attach a new one here? Thanks.

2022-04-18 21:16 UTC, jaredcwhite commented
> touched base offline with @slowbot, we will be adding back this latest listings scroll piece in the relatively near future, so we'd like to just comment it out and not remove it so that it's easy to add back in later

@emilyjablonski Yeah it's still in there, just "switched off" in a feature flag-y way. Easy to switch back on later.

2022-04-19 23:44 UTC, jaredcwhite commented
OK, I think all feedback's now been addressed, pending those two questions for @slowbot. One other thing I noticed: we should use the newer envelope & doorway icons for the new CTAs, but we'd need another sync from Bloom core dev in order to do that.

2022-04-20 21:45 UTC, seanmalbert commented
@YazeedLoonat and @slowbot , you both requested changes, can you please review and approve if it looks good. @slowbot , there is also a question for you from @jaredcwhite above.

2022-04-21 16:45 UTC, YazeedLoonat approved these changes
LGTM

2022-04-21 20:34 UTC, jaredcwhite commented
Leaving a note here for followup as well (after a convo with Jesse) that we're hoping to get a better resolution version of the image. But I'll add what we got for now in order to merge.

2022-04-21 21:16 UTC, merged