fix: error when passing empty string as phone number to usToIntlPhone…
CityOfDetroit/bloom pull request #1160
Opened 2022-04-19 21:05 UTC by adriencyberspace

… helper

- Closes #1123 

## Description

Despite phone number not being required to create a new account, an invalid phone number error was being thrown when a user does not include a phone number. This PR fixes that error.

## How Can This Be Tested/Reviewed?

Entry Point: http://localhost:3000/create-account

Create a new account with all required fields. Do not include a phone number. Sign up should be successful. 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-04-20 15:43 UTC, emilyjablonski commented
@YazeedLoonat I worked with Adrien here, so would love your review

2022-04-20 23:19 UTC, seanmalbert requested changes

2022-04-20 23:19 UTC, seanmalbert commented on sites/public/lib/helpers.tsx
>  export const usToIntlPhone = (usPhoneNumber: string): string => {
Since `null` is now a possible return of `usToIntlPhone`, can you please update the return type to reflect that.

2022-04-20 23:19 UTC, seanmalbert commented on sites/public/lib/helpers.tsx
>  export const intlToUsPhone = (intlPhoneNumber: string): string => {
Can you also update `intlToUsPhone`.

2022-04-21 18:17 UTC, adriencyberspace commented
#1163 Connecting this issue here - which addresses the failed checks here.

2022-04-25 06:28 UTC, YazeedLoonat approved these changes
LGTM

2022-04-25 14:01 UTC, merged