1096/tooltip
CityOfDetroit/bloom pull request #1175
Opened 2022-04-25 14:52 UTC by dominikx96

## Issue

- Closes #1096
- Addresses #1096
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Adds a tooltip component that is visible in a "confirmed property" tag and info icon (units table) on a public listing page.

## How Can This Be Tested/Reviewed?

1. Open a listing with the "confirmed by property" status
2. Hover on the "confirmed by property"
3. Focus on the "confirmed by property"
4. Hover on the "info" icon next to the "AMI" header table 
5. Focus on the"info" icon next to the "AMI" header table
6. In points 2-5 you should see a tooltip

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [x] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-04-25 17:10 UTC, emilyjablonski commented on ui-components/src/blocks/Tooltip.scss
> +  @apply capitalize;
I don't think we want capitalize here based on the mock

2022-04-25 17:12 UTC, emilyjablonski requested changes
Lookin good! A couple things:
* I'm not able to keyboard focus on the AMI icon 
* The AMI icon is not visible on mobile view, bc of the different table views, not sure if we want it to be visible somewhere? Additionally on mobile should clicking the tooltip again dismiss it? @slowbot

2022-04-25 17:13 UTC, emilyjablonski commented on ui-components/__tests__/blocks/Tooltip.test.tsx
> +import React from "react"
🥳

2022-04-25 17:15 UTC, emilyjablonski commented on ui-components/src/blocks/Tooltip.tsx
> +const Tooltip: React.FC<TooltipProps> = ({ className, id, text, children }) => {
We don't use the `React.FC` notation, so let's use the generic functional component notation

2022-04-25 17:15 UTC, emilyjablonski commented on ui-components/src/tables/GroupedTable.tsx
> +      <>
We can remove this fragment

2022-04-26 15:20 UTC, dominikx96 commented
@emilyjablonski thanks for the review! 

```
The AMI icon is not visible on mobile view, bc of the different table views, not sure if we want it to be visible somewhere? Additionally on mobile should clicking the tooltip again dismiss it? @slowbot
```

It needs a table component refactor so before I start doing it, please confirm that we need it on mobile too :)

2022-04-26 16:27 UTC, emilyjablonski commented
Waiting on feedback from @slowbot before making any changes 👍

2022-04-27 16:23 UTC, emilyjablonski approved these changes
https://user-images.githubusercontent.com/65367387/165565998-58c9866b-9d53-4e3a-8582-24abcbd452e0.mov

This looks great! The scroll bug above is my only remaining question, but I think it might be fine to merge over and handle in a followup, I'll check in and let you know

2022-04-27 17:11 UTC, YazeedLoonat reviewed
Not sure if this should block merging this in, right now on mobile the `Coming Soon` Tooltip pops up when you click on "coming soon" which flashes the tooltip before being redirected away 
I think we do want to remove the tooltip for that on mobile

2022-04-27 20:13 UTC, emilyjablonski commented
@YazeedLoonat That seems to only happen on the directory page, I'm personally good to handle it in a followup but happy either way

2022-04-27 20:37 UTC, merged