1344/prominent filter button
CityOfDetroit/bloom pull request #1387
Opened 2022-07-11 22:42 UTC by ColinBuyck

# Pull Request Template

## Issue Overview

This PR addresses #issue

- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-07-13 17:17 UTC, emilyjablonski requested changes
![Screen Shot 2022-07-13 at 11 14 56 AM](https://user-images.githubusercontent.com/65367387/178792318-7b2ceda5-e380-4678-885e-7a3d55c4a6f0.png)
The hover state for the filter button has the icon as a white color, but on detroit dev right now looks like there is no hover state on the filter button so I imagine it should stay black. Additionally the string in the design is not capitalized, but it is in the issue, so I would check in with Jesse super quick about whether or not it should be capitalized.

2022-07-13 19:13 UTC, ColinBuyck commented
@emilyjablonski Good catches! I confirmed the string casing with Jesse and fixed the hover issue. Let me know if there's anything else I can fix!

2022-07-13 22:14 UTC, emilyjablonski commented on ui-components/src/locales/bn.json
>  {
Do you know what caused these diffs in `bn.json` and `ar.json`? Is it maybe a prettier setting you have or a tab size setting?

2022-07-13 22:26 UTC, emilyjablonski approved these changes
Looks like the formatting changes in the translation files are expected as dev is for some reason inconsistent with prettier 👍 LGTM

2022-07-19 01:30 UTC, seanmalbert commented
@ColinBuyck , can you resolve the merge conflicts. You're good to merge after that.

2022-07-19 17:09 UTC, merged