1348/partners listing search
CityOfDetroit/bloom pull request #1407
Opened 2022-07-26 18:39 UTC by ColinBuyck

# Pull Request Template

## Issue Overview

This PR addresses #issue

- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-07-27 15:32 UTC, emilyjablonski requested changes
![Screen Shot 2022-07-27 at 9 28 49 AM](https://user-images.githubusercontent.com/65367387/181288201-4b02236a-b796-47f3-bafd-eda9c96748c5.png)
This is looking great, just one small fix on alignment of the helper text box on mobile

2022-07-27 15:32 UTC, emilyjablonski commented on sites/partners/pages/index.tsx
> +  //   NavigationHeader,
🧹

2022-07-27 18:02 UTC, ColinBuyck commented
Good Catches @emilyjablonski! Those issues should be resolved now. Also, noticing that the centering issue is present in core as well so I can make those component updates once this PR is finalized.

2022-07-30 01:29 UTC, emilyjablonski approved these changes

2022-08-09 17:04 UTC, merged