refactor: remove duplicate reseed command
CityOfDetroit/bloom pull request #1518
Opened 2022-12-08 20:46 UTC by emilyjablonski

Remove the duplicate reseed command
To test:
A local reseed should seed the Detroit listings
The Travis CI tests should pass

2022-12-09 15:55 UTC, ludtkemorgan requested changes

2022-12-09 15:55 UTC, ludtkemorgan commented on backend/core/package.json
> +    "ioredis": "^4.24.4",
Looks like this should be the 5.2.3 instead of the 4.24.4

2023-01-20 20:09 UTC, ludtkemorgan commented on backend/core/package.json
> -    "db:seed": "ts-node src/seeder/seed.ts",
with this change the only reference to `seed.ts` is the `test:db:setup` task. Should we also remove it from there as well?

2023-01-20 20:10 UTC, ludtkemorgan commented on backend/core/package.json
> -    "db:seed": "ts-node src/seeder/seed.ts",
As an addition to that, should we also remove the seed.ts file altogether?

2023-02-14 15:50 UTC, emilyjablonski commented
Tests fail removing this file, working on getting those aligned

2023-08-24 00:44 UTC, closed without merging