feat: add user csv export
CityOfDetroit/bloom pull request #1560
Opened 2023-02-21 23:21 UTC by ludtkemorgan

# Pull Request Template

## Issue Overview

This PR addresses #issue

- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2023-03-07 19:34 UTC, ludtkemorgan commented
@ColinBuyck I have fixed the tests and they are now running on Travis. You should be able to use the same pattern in your changes

2023-03-07 23:01 UTC, emilyjablonski commented on sites/partners/__tests__/testHelpers.ts
> +    city: "San Jose",
Nit: Could be a Detroit address

2023-03-07 23:01 UTC, emilyjablonski commented on sites/partners/cypress/integration/admin-user-mangement.spec.ts
> +  it("as admin user, should show all users regadless of jurisdiction", () => {
`regardless`

2023-03-07 23:12 UTC, emilyjablonski requested changes
I'm not getting an error or sucess toast / alert but otherwise lgtm!

More of a question, but not sure we need `Partner` if we also have `Administrator`
<img width="137" alt="Screenshot 2023-03-07 at 4 08 24 PM" src="https://user-images.githubusercontent.com/65367387/223575219-1c224818-2d30-4ab1-a713-e06e69ed5dac.png">

2023-03-08 19:14 UTC, ludtkemorgan commented
@emilyjablonski Good catch about the alert. That has been fixed.

For the `Administrator, Partner` I followed the same structure as it is on the table. I don't think in production that use case is going to come up. But the data in dev has it.

2023-03-09 04:49 UTC, ColinBuyck reviewed
This is looking good 🐩 just two things: It looks like the export success alert is still missing. Also, I'm wondering if you think it would be worth it to add unit tests for the error message and success message showing here as we were working on for the Detroit Listings Export.

2023-03-09 17:46 UTC, emilyjablonski approved these changes
🚈

2023-03-10 22:46 UTC, merged