Linkify eligibility nav bar
CityOfDetroit/bloom pull request #433
Opened 2021-08-19 18:12 UTC by abbiefarr

## Issue

Addresses #263 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Allows the nav bar buttons to be linkified and provides links for the eligibility questionnaire. Users can now navigate back and forth by clicking the nav bar and still see their progress.

![image](https://user-images.githubusercontent.com/83078310/130122079-e57571ad-e040-49cc-bb0a-174e9546e7f8.png)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Prototype/POC (not to merge)
- [ ] This change is a refactor/address technical debt
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

Pull up the eligibility questionnaire and click around!

- [x] Desktop View
- [x] Mobile View

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have updated the changelog to include a description of my changes

2021-08-19 18:18 UTC, willrlin requested changes
When you start clicking through the eligibility questionnaire, on the first click the page stays the same but the yellow dots move and on the second click you go to the next page.

2021-08-19 18:31 UTC, abbiefarr commented
Huh... that's weird, mine doesn't do that locally. I do see a slight lag where the yellow dot appears and then it turns green, but the page changes without a second click.

2021-08-19 19:26 UTC, abbiefarr commented
Fixed the lag!

2021-08-23 13:31 UTC, willrlin approved these changes
Can you file a bug for the fact that clicking back after clicking on some of the headings always requires 2 back presses? One goes to `../income#` and then the next back press goes to `../income`.

2021-08-23 14:04 UTC, merged

2021-08-23 14:04 UTC, abbiefarr commented
Filed #442